# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trap', '0002_auto_20150710_1447'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='req_records',
            new_name='ReqRecords',
        ),
    ]
