# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trap', '0003_auto_20161017_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traps',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(verbose_name=b'Creation time of the trap')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='reqrecords',
            name='rem_ip',
            field=models.GenericIPAddressField(verbose_name=b'Field for IP addresses'),
        ),
    ]
